### PLEASE READ BELOW BEFORE PROCEEDING TO EDIT ###
# FOR CONTRIBUTORS:
# Do not edit this file! The maintainers will handle the rest for you in most cases.
#
# FOR MAINTAINERS:
# Before you ever add new feed entries here, please read the included README
# and any Python code comments. Not fllowing may cause chaos and even blocking
# your merge request from ever merging automagically.
#
# In case the Atom feed file itself has merge conflicts right after rebasing
# or just an simple git pull from upstream, immediately fix any conflicts in
# this file, HERE, and the run the following command to fix it:
#
#     yarn rss-generator:recent && git add . && yarn commit
#
# When prompted in the Commitizen part, select chore as scope, rss-feeds as type
# and "resolve conflcts in utils/rss directory" as commit title.
### PLEASE READ ABOVE BEFORE PROCEEDING TO EDIT

from datetime import datetime, timezone
from rfeed import *

# DO NOT REMOVE THIS OR THINGS MIGHT BREAK! If you ever moving stuff to the historical_activity.py file,
# it's fine not to include this section, but please, do not remove this!
initialEntry = Item(
        title = "Placeholder Content",
        link = "https://gitlab.com/RecapTime/verify",
        description = "Jsut an simply placeholder since you reached the end or the feed isn't updated yet.",
        author = "Recap Time Bot",
        guid = Guid("https://gitlab.com/RecapTime/verify"),
        # When updating published date, remember thee format YYYY, MM, DD, HH, MM and use UTC timezone
        # as much as possible.
        pubDate = datetime(2021, 9, 12, 11, 45, tzinfo=timezone.utc))

### DO NOT ADD NEW ENTRIES RIGHT BELOW THIS LINE, ADD NEW ONES ABOVE THIS LINE INSTEAD. ###

feed = Feed(
        title = "Historical Manifest Changes for verify.rtapp.io registry",
        link = "https://gitlab.com/RecapTime/verify",
        description = "Currently manually-maintained Atom feed for every signle manifest changes in @rtapp-verify/list-manifests Yarn workspace.",
        language = "en-US",
        lastBuildDate = datetime.now(timezone.utc),
        # Override some values rfeed ever set btw
        docs = "https://github.com/RecapTime/verify/blob/main/utils/rss/README.md", # Point to utils/rss README in main branch
        generator = "rfeed https://github.com/svpino/rfeed/commit/a4ccbcb4", # submodule stuff here KEK
        # Add entries here, remember about JSON right?
        items = [initialEntry])

print(feed.rss())

