name: Verify an content creator, entity or community
description: |
  Use this issue form to submit an verification request as an GitHub issue. GitLab users must fill up the issue based on the provided AddNewEntry issue template.
title: "Request to verify Entry Name Here"
labels:
  - "request-forms:new-entries"
  - "enhancement"
assignees:
  - RecapTimeDquad
  - ThePinsTeam

# The main form goes here! For maintainers and contributors who wish to improve this form should consult
# our YAML schema JSON file at https://github.com/RecapTime/verify/blob/main/.vscode/schemas/custom-yaml.json and
# the documentation for details. If the official GitHub Issues and Pull Requests extension isn't installed
# or not using VS Code should consult the YAML schema we checked in at https://github.com/RecapTime/verify/blob/main/.vscode/schemas/gh-issue-forms.json
# and the GitHub docs at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms.
# Hopefully GitLab will also support issue forms too in the future.
body:
  - type: markdown
    attributes:
      value: |
        Hey contributor! Thanks for helping us verifying more creators, communities and companies. Use this GitHub issue form to sumbit an new entry to shoot into the backlog.

        Remember that you need to do your own homework in researching for an specific entry before filling and submiting this form. An incomplete form will make our lives even harder and possibly will be closed.
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing issue for this request on GitLab?
      description: Please search to see if an issue already exists for the request you're about to submit. If you found one but closed due to any reasons, please read our maintainers' feedback before you submit a new one. If you found an existing open issues, feel free to send an merge request on GitLab.
      options:
      - label: I have searched the existing issues
        required: true
  # Slug name
  - type: input
    id: slugName
    attributes:
      label: Please enter the desired slug name.
      description: This value will be used for maintainers and other contributor to submit an PR and to create an manifest file with YML extension within `lists/<category>` directory of the default Git branch. Only small letters, numbers and dashes are supported due to API backend compartibility reasons.
      placeholder: slug-name
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: What's the short/screen name of this entry?
      description: |
        For content creators, its their screen name. For communities and publishers (book publishers, music labels, any entities that publish stuff on BEHALF of content creators), it usually their public company or community name. It possible that an community has it own legal entity in terms of finanical and copyright stuff (for example the KDE Community has KDE e.V. for finanical and copyright matters, but only the KDE Community will counted here since we don't support any other types of companies/entities other than content publishers/licensors yet)

        Remember to place the placeholder `Entry Name Here` with the value of this field before you continue filling this form up.
      placeholder: Entry Name Here
    validations:
      required: true
  - type: input
    id: legalName
    attributes:
      label: What's the full or legal name of this entry?
      description: This is an optional field, but recommended to fill up if so. For content creators, its either their full or legal name. If their full name isn't public yet, try to use their first name from an source (YouTube Wikia, etc.) for now. For publishers, its their full company name. Communities without EITHER an legal entity OR the longer version of their community name should leave this blank.
  - type: dropdown
    id: submissionType
    attributes:
      label: Select an submission type for this request
      description: |
        **Glossary for new contributors**:

        * Content Creator are music artists, OSS developers and maintainers, and simply put any public figure that are either politicans and criminals are excluded.
        * Entity are organizations or companies with atleast 2 or more people. Most companies and non-profits usually fall here.
        * Communities are pretty self-explainatory, right? They're either built by either an Content Creator or Entity.
      options:
        - Content Creator
        - Community
        - Entity
    validations:
      required: true
  - type: textarea
    id: socials
    attributes:
      label: Social links
      description: Social links for an specific entry. At least one working social link in order to be accepted in the main RecapTime/verify GitHub repo.
      placeholder: |
        * https://twitter.com/username - has verified badge
        * https://youtube.com/chammel/channelIdoverHereUwU - fan account
        * https://matrix.to/#/#twim:matrix.org
        * https://lttstore.com - merch site
        * https://discord.gg/gildedguy - just an regular Community server with Booster Level 3
    validations:
      required: true
  ## Annonations - START ##
  - type: markdown
    attributes:
      value: |
        ## Entry Annonations

        This section is where all currently supported and future annonations where you can fill up goes here. They are always optional and you can skip them altogether.
  - type: checkboxes
    id: oss-maintainership-status
    attributes:
      label: Open-source Maintainership Status
      description: |
        **ONLY APPLIES TO CONTENT CREATORS, SKIP IF ITS AN COMPANY OF ANY SORT OR COMMUNITY!**

        Check any boxes where this entry is actively maintains in the following open-source projects. Any past projects where this developer maintains should be noted in the comments field below.
      
        Can't found it? Pick `Other open source projects` and provide us the open-source project name, link to website/repository in the comments section of this form for details. If this entry doesn't maintain any OSS projects, please do not tick anything.
      # Alphabettical order, please!
      options:
        # debian.org/active-distro-maintainer
        - label: Debian (<https://debian.org>)
        # gitlab.com/active-maintainer, note that we'll check if he/she is an GitLab team member or not.
        - label: GitLab (<https://gitlab.com/gitlab-org/gitlab)
        - label: VS Code (<https://github.com/microsoft/vscode>)
        - label: Other open source projects (list down in the comments field below)
  ## Annonations - START ##
  - type: textarea
    id: comments
    attributes:
      label: Any comments our maintainers want to know?
      description: Please only note any extra information you might want to submit for this entry. Check the docs on what to place in this field.
      value: |
        <!--

        Please remove everything by hitting Ctrl+A and then Backspace while the cursor is within this textarea.
        Check the documentation for details about this section.

        -->
        #### OSS Projects with Active Maintainership Status

        When linking, please use either the project's homepage, documentation site or the source code itself.

        * Project name - <https://example.org>

        ### OSS Projects with Past Maintership Status

        When linking, please use either the project's homepage, documentation site or the source code itself.

        * Project name - <https://example.org>

        ## Discord Account Association

        Our Discord bot should generate one of these metadata below for validation purposes only.

        * Account ID: 1234567890
        * Server ID where /verify is triggered: 1234567890
  - type: markdown
    attributes:
      value: |
        ---
        
        By submitting this form, you agree to [Recap Time Community Code of Conduct](https://github.com/MadeByThePinsHub/policies/blob/trunk/CODE_OF_CONDUCT.md) and our [Entry Submission Guidelines](meta/SUBMISSION_GUIDELINES.md). You also certify that all information you submit is accurate and true by the time you submit this issue.