// adopted from https://github.com/electron/apps/blob/master/lib/app-categories.js, send us an PR/MR
// to improve this list.
module.exports = [
  'Books',
  'Business',
  'Catalogs',
  'Developer Tools',
  'Education',
  'Entertainment',
  'Finance',
  'Food & Drink',
  'Games',
  'Health & Fitness',
  'Graphics & Design',
  'Lifestyle',
  'Kids',
  'Magazines & Newspapers',
  'Medical',
  'Music',
  'Navigation',
  'News',
  'Photo & Video',
  'Productivity',
  'Reference',
  'Shopping',
  'Social Networking',
  'Sports',
  'Travel',
  'Utilities',
]
